### ISSUE TITLE
PackageManager

### ISSUE THREAD

**Issue by WangEdgar** [CesiumGS/cesium-unity-samples#27]
https://unity.pkg.cesium.com
Access denied
"Cannot connect to 'github.com' (error code: ECONNRESET). Verify your environment firewall policies allow connection to this host name. lfour system is behind a proxy, verify your proxy environment varlables (HTTP_PROXY and HTTPS_PROXY) are properly set."

**Comment by kring** [comment]
This looks like the same issue as reported here:
https://community.cesium.com/t/launching-cesium-for-unity/21380/6
I'm closing this as it's almost certainly a problem with your system or network, not something we can fix on our end. Please start a thread on the community forum if you have any followup questions.
