### ISSUE TITLE
How can I manually download Cesium for Unity using the Package Manager 

### ISSUE THREAD

**Issue by yanivday** [CesiumGS/cesium-unity-samples#34]
Hi,
I would like to start a new project from scratch, and not from the sample project. How can I manually download Cesium for Unity using the Package Manager?

**Comment by kring** [comment]
See the [Quick Start](https://cesium.com/learn/unity/unity-quickstart/). Please post followup questions to the [community forum](https://community.cesium.com/c/cesium-for-unity/13); we use GitHub issues only for bug reports and feature requests.
