### ISSUE TITLE
support for webgl build

### ISSUE THREAD

**Issue by AdrienHoule** [CesiumGS/cesium-unity-samples#35]
Do you intend to make this plugin compatible with webgl build? Because for now I've to compile in it in webgl and couldn't succeed. 
I would love to have the ability to compile it in webgl and various desktops.

**Comment by kring** [comment]
We may eventually support WebGL, but not any time soon. Cesium for Unity uses a substantial amount of native code, so compiling for WebGL is quite challenging. Please post followup questions to the [community forum](https://community.cesium.com/c/cesium-for-unity/13); we use GitHub issues only for bug reports and feature requests.

**Comment by kring** [comment]
By the way, if you're targeting WebGL, you may be interested in CesiumJS:
https://github.com/CesiumGS/cesium#readme
