### ISSUE TITLE
can not run the project

### ISSUE THREAD

**Issue by JL13sky** [CesiumGS/cesium-unity-samples#53]
<img width="1016" alt="image" src="https://github.com/CesiumGS/cesium-unity-samples/assets/119465391/e97d8753-f983-4fca-982a-3375e727358b">

**Comment by kring** [comment]
Cesium for Unity is loaded from an package registry hosted at https://unity.pkg.cesium.com/-/all/. Perhaps your system or network is blocking access to it?

In any case, please follow up on the [community forum](https://community.cesium.com/c/cesium-for-unity/13). We use github for confirmed bug reports and feature requests.
