### ISSUE TITLE
🥽 1️⃣ VR Level 1 - Denver Photogrammetry - Crashing Every Time On Oculus Quest 2

### ISSUE THREAD

**Issue by williamswarren** [CesiumGS/cesium-unity-samples#54]
Not sure what is the best way to run this sample project.

- It runs in the Unity Editor no problem
- It builds the apk without issues
- It either crashes fairly quickly when launching on the headset or after moving around a little bit (once the scene loads)

I have played quite a bit with the different parameters on the Aerometrex Denver Photogrammetry GameObject, but cannot seem to find the right things to tweak?

**Comment by joseph-kaile** [comment]
Hello, I would look at the Screen Space Error and increase it. Also, try setting the Maximum cached bytes parameter to 0.

**Comment by williamswarren** [comment]
Hi Joseph, thanks for the reply, I tried setting both Screen Space Error to an insanely large number as well as Maximum Cached Bytes to 0 and it still crashes unfortunately.

**Comment by kring** [comment]
What is the call stack of the crash?

**Comment by williamswarren** [comment]
[odh_logs_2023-05-25 05.35.36.027.txt](https://github.com/CesiumGS/cesium-unity-samples/files/11561464/odh_logs_2023-05-25.05.35.36.027.txt)

~22:29 is when I launch the app on the Quest 2

**Comment by kring** [comment]
Do you know approximately what time the crash happened @williamswarren? There's a lot of stuff in there, but the moment when it crashes is not obvious at all. I expected to see a segfault or something, but there doesn't seem to be anything like that.

@joseph-kaile can you reproduce this on your Quest 2?

**Comment by williamswarren** [comment]
@kring  I will try narrow it down, it was not very clear to me either.

**Comment by williamswarren** [comment]
<img width="1158" alt="Screen Shot 2023-05-24 at 11 32 21 PM" src="https://github.com/CesiumGS/cesium-unity-samples/assets/56812538/80d2945e-6f3b-4bd5-9cb1-d3e4e07c6c4d">
<img width="1515" alt="Screen Shot 2023-05-24 at 11 33 39 PM" src="https://github.com/CesiumGS/cesium-unity-samples/assets/56812538/a76e33e1-9c8e-4c54-8ca0-b2744f7922d9">
<img width="1514" alt="Screen Shot 2023-05-24 at 11 34 10 PM" src="https://github.com/CesiumGS/cesium-unity-samples/assets/56812538/3ae4f1f3-11ed-4a4c-bbac-003b0b4f5d45">

These seem to be some of the more salient error messages when going through the logs. Something to do with Vulkan maybe?

**Comment by joseph-kaile** [comment]
I recall some older version of Unity had an issue with Vulkan but it was fixed in a newer release. 

Secondly, this may not fix the issue, but switching from OpenXR to Oculus may help. It helped me get rid of some performance and rendering problems.

**Comment by williamswarren** [comment]
Great, thanks @joseph-kaile , I will give your suggestions a try!

**Comment by williamswarren** [comment]
<img width="1588" alt="Screen Shot 2023-05-25 at 10 32 01 PM" src="https://github.com/CesiumGS/cesium-unity-samples/assets/56812538/916861c4-c679-46cf-b1fa-9e4162fa958d">

Can confirm it runs buttery smooth when following what @joseph-kaile said and changing from OpenXR to Oculus!

Thanks for the help everyone, left a screenshot for others showing my Unity version and what Joseph suggested, not sure if this is a problem everyone will face, but might be worth updating the info banner in the scene @kring so that others will know to try Oculus in case OpenXR does not work for them!
