### ISSUE TITLE
Low fidelity building models on mac and iOS

### ISSUE THREAD

**Issue by yuchenz27** [CesiumGS/cesium-unity-samples#55]
<img width="836" alt="image" src="https://github.com/CesiumGS/cesium-unity-samples/assets/44870300/c1783622-6a39-4dab-bd39-435db1a7b3d9">

When I was runing the project on mac and iOS devices, all building models were in low fidelity mode. I didn't change anything in the project. How can I get high fidelity building models?

My environment:

Unity 2021.3.22f1
macOS 12.6
iPhone 13 Pro
iOS 16.3.1

**Comment by kring** [comment]
Please post to the [community forum](https://community.cesium.com/c/cesium-for-unity/13). We use github issues only for confirmed bugs and feature requests.

When you do, please include more detail about what you're expecting. Is the screenshot the "low fidelity" version? I don't know what "high fidelity" is, but if you can share a screenshot of it I might understand what you mean.
