### ISSUE TITLE
Render costum LineString

### ISSUE THREAD

**Issue by dmenneck** [CesiumGS/cesium-unity-samples#59]
Hello all, 
is it possible to display a LineString (WGS84) in a Cesium Unity world? The LineString comes from a routing engine (via http get request) and should allow to navigate from one place to another.

**Comment by kring** [comment]
Please post questions like this to the [community forum](https://community.cesium.com/c/cesium-for-unity/13).

Cesium for Unity doesn't have any built-in support for rendering lines, but you may be able to find something built in to Unity (or available as a plugin) to do it. Where Cesium for Unity can help is it provides methods on the CesiumGeoreference object that allow conversion of WGS84 longitude/latitude/height to Unity world coordinates.
