### ISSUE TITLE
any chance to support webgl platform?

### ISSUE THREAD

**Issue by cardinalblues7** [CesiumGS/cesium-unity-samples#63]
Thanks for this amazing plugin.
Our project has to use cesium in webgl.Any plans for this to come true? Thank you

**Comment by kring** [comment]
This has been asked many times on the [community forum](https://community.cesium.com/c/cesium-for-unity/13). Cesium for Unity uses native code so WebGL support is unlikely to happen anytime soon. If you're targeting WebGL, we suggest using [CesiumJS](https://github.com/CesiumGS/cesium) instead.
