### ISSUE TITLE
UI tabletop-like Map

### ISSUE THREAD

**Issue by sdi1900012** [CesiumGS/cesium-unity-samples#68]
Hello,

I am currently developing an app for magic leap 2 ar glasses. Is it possible to create something like a small UI tabletop map using cesium sdk or should i look for alternatives? i am asking this because in all the demo scenes the map is covering the entire scene as it is intented for a full immersive experience.

**Comment by azrogers** [comment]
Hi @sdi1900012, thanks for the question! You can accomplish something like this by extending the [CesiumTileExcluder](https://github.com/CesiumGS/cesium-unity/blob/main/Runtime/CesiumTileExcluder.cs) component in Cesium for Unity. In the future, I'd recommend asking questions like this on the [community forums](https://community.cesium.com/c/cesium-for-unity/13). You'll be more likely to get a quick response to your questions there!
